package records;

/**
 * Demonstrates Java record usage: a compact, immutable data carrier.
 * The nested User record auto-generates constructor, accessors,
 * equals(), hashCode(), and toString().
 */
record User(String name, int age) {
    // Records are implicitly final and provide read-only accessors.
}

/**
 * Runner class with a simple main method to show record usage.
 */
public class Runner {
    public static void main(String[] args) {
        // Create a User record instance
        User kim = new User("Kim", 29);

        // Accessors generated by the record: name() and age()
        System.out.println(kim.age());  // prints age
        System.out.println(kim.name()); // prints name

        // Demonstrate equals/hashCode behavior for records
        User kim2 = new User("Kim", 29);
        System.out.println(kim.hashCode());
        System.out.println(kim2.hashCode());
    }
}

